export const ACTION_OAUTH_REQUEST_ACCESS_TOKEN = "ACTION_OAUTH_REQUEST_ACCESS_TOKEN"
export const ACTION_OAUTH_REQUEST_VIEWER_INFO = "ACTION_OAUTH_REQUEST_VIEWER_INFO"
export const ACTION_SIGN_OUT = "ACTION_SIGN_OUT"