export const CROSS_MUTATION_TRIGGER_LOADING = "TRIGGER_LOADING"

export const CROSS_MUTATION_RESOLVE_DATA = "CROSS_MUTATION_RESOLVE_DATA"

export const CROSS_MUTATION_TRIGGER_FLAG = "CROSS_MUTATION_TRIGGER_FLAG"

export const CROSS_MUTATION_CANCEL_AND_UPDATE_AXIOS_CANCEL_TOKEN_SOURCE = "CROSS_MUTATION_CANCEL_AND_UPDATE_AXIOS_CANCEL_TOKEN_SOURCE"


