export const CROSS_MUTATION_TRIGGER_LOADING = "TRIGGER_LOADING"

export const CROSS_MUTATION_RESOLVE_DATA = "CROSS_MUTATION_RESOLVE_DATA"

export const CROSS_MUTATION_TRIGGER_FLAG = "CROSS_MUTATION_TRIGGER_FLAG"


